#!/usr/bin/env bash

# Look for UV and install it if not present
if ! command -v uv &> /dev/null
then
    echo "Install uv with 'curl -LsSf https://astral.sh/uv/install.sh | sh'"
    exit 1
fi

# Send output to junk
uv sync && \
    uv run ty check financial_analysis && \
    uv run ruff check --fix --unsafe-fixes financial_analysis && \
    uv run pytest -q && \
    uv run financial_analysis -c ${1}
