WHITELIST = [
            "aapl",
            "ait",
            "cron",
            "nvda",
            "amzn",
            "amd",
            "f",
            "intc",
            "msft",
            "pcg",
            "gpc",
            "ge",
            "jakk",
        ]